package com.budjb.asynchronoustasks

class AsynchronousTaskDomain {
    /**
     * Percentage complete the task is.
     */
    int progress = 0

    /**
     * Name of the operation the task represents.
     */
    String name

    /**
     * A description of task.
     *
     */
    String description

    /**
     * The current operation the task is performing.
     *
     * This is useful to provide insight into what step a long running process is in.
     */
    String currentOperation

    /**
     * State of the task.
     */
    AsynchronousTaskState state = AsynchronousTaskState.NOT_RUNNING

    /**
     * Time when the task was initially created.
     */
    Date dateCreated

    /**
     * Time when the task was started.
     */
    Date startTime

    /**
     * Time when the task ended.
     */
    Date endTime

    /**
     * Last time the row was updated.
     */
    Date lastUpdated

    /**
     * Data for the task.
     *
     * This field is useful to store results or error information generated by the task.
     */
    String results

    /**
     * Data associated with the task used to store process state.
     *
     * This data field is not intended to be exposed to the user.
     */
    String internalTaskData

    /**
     * Name of code of the error.
     */
    String errorCode

    /**
     * Resolution suggestion/code
     */
    String resolutionCode

    /**
     * Field constraints.
     */
    static constraints = {
        lastUpdated nullable: true
        dateCreated nullable: true
        startTime nullable: true
        endTime nullable: true
        description nullable: true
        results nullable: true
        internalTaskData nullable: true
        errorCode nullable: true
        currentOperation nullable: true
        resolutionCode nullable: true
    }

    /**
     * DB mapping.
     */
    static mapping = {
        version false
        results type: 'text'
        internalTaskData type: 'text'
    }
}
